### ISSUE TITLE
City name incorrect

### ISSUE THREAD

**Issue by miljanrajkovic** [DesconBelgrade/Klimerko#11]
I noticed a bug with detecting a city name from the GPS position on the web application, My Klimerko is positioned well on the map (in Niš), but for some reason there is label Aleksinac on the page.

![image](https://user-images.githubusercontent.com/7680939/97877976-4d6ac780-1d1e-11eb-97f9-6db973262826.png)

**Comment by epiller** [comment]
Sorry for the late reply - could you check now?

**Comment by miljanrajkovic** [comment]
It has been working fine from few months ago. Thanks.
