### ISSUE TITLE
Not visable on the map

### ISSUE THREAD

**Issue by nexbg** [DesconBelgrade/Klimerko#16]
Hi, friend of mine and myself  assembled 1 measuring station. Everything has been set and we can see that station is up and running, measuring, and it is "shared" via AllThingsTalk . 

However, we can not see it on "Vazduh gradjanima" page, even we have location set up. 

Do you know what could be a problem?

**Comment by epiller** [comment]
That's odd. Could you send me the Device ID of your Klimerko?

**Comment by nexbg** [comment]
7b7a5oXyJeO9JCk8r7jXGeG8

**Comment by epiller** [comment]
Fixed!
