### ISSUE TITLE
Bridge connector for PMS7003 

### ISSUE THREAD

**Issue by nexbg** [DesconBelgrade/Klimerko#17]
Hi, 

in the package we have ordered we have not received bridge connector with cables. Is there any suggestion from your end for alternative solution?

For a test purpose we have soldered wires to pines directly (we have found scheme on internet), but it is not the best solution since wires can be moved and even run into short circuit. 

Thank you in advance.

**Comment by epiller** [comment]
[I found this on AliExpress](https://www.aliexpress.com/item/32780006665.html), but the shipping prices are awful. 
If you can't order from AliExpress, try buying another PMS7003 from somewhere else and ask the seller to provide you with more "G7 Adapters" (bridge board).
The first time I played with PMS7003 I also forgot the bridge board and did the same thing as you - soldered it by hand. It still holds to this day, but you should definitely avoid that as a solution.
