### ISSUE TITLE
3D case instruction

### ISSUE THREAD

**Issue by mletic** [DesconBelgrade/Klimerko#2]
Is there any way to order the 3D case? 
Or at least to get the 3D model and the relevant info so we can print it somewhere?

Btw keep up the good work!

**Comment by DesconBelgrade** [comment]
There isn't right now, but it'll be available in the near future!
And thanks :)

**Comment by epiller** [comment]
Hey, thought I'd you know that the required to 3D print the case yourself have just been published and you can check them out [here!](https://github.com/DesconBelgrade/Klimerko/tree/master/Klimerko_Printable_Case)
