### ISSUE TITLE
Znakovi u wifi sifri?

### ISSUE THREAD

**Issue by y0d4a** [DesconBelgrade/Klimerko#23]
Zdravo, imam problem da nakacim klimerka na wifi koji sadrzi npr. ! karakter u sifri..
Jel to by design :) od strane esp-a ili?

**Comment by epiller** [comment]
Mozes li malo bolje opisati problem? (npr. U kom dijelu procesa se to desava? Da li ne dozvoljava pri unosu ili se samo na spaja?)

**Comment by y0d4a** [comment]
Dozvoli sve unose i posle restarta, nikako da se poveze, samo tacke redja...
`Connecting to WiFi: wifi_iot..............................................................................................................................................................`

Na routeru vidim stalno `E0:98:X:X:X:X@wifi_iot: disconnected, received deauth: sending station leaving (3)`

**Comment by epiller** [comment]
- Probaj iskljuciti Klimerka iz struje komplet pa opet ukljuciti nakon 1 min.
- Provjeri da li imas najbovije verzije Klimerko Firmware-a, ESP8266 Core-a i Arduina
- Ako uklonis "!" iz sifre na ruteru, da li se onda spaja?

**Comment by y0d4a** [comment]
**moja je greska bila**, ceo taj wifi sam onesposobio zbog nekog testa i nisam vratio na stare vrednosti :)
sve ok radi, zatvaram case.
