### ISSUE TITLE
Error while uploading the sketch on MacOS Big Sur

### ISSUE THREAD

**Issue by selkuncik** [DesconBelgrade/Klimerko#24]
I followed your instructions for firmware upload but got an error when I tried to upload the firmware. Didn't copy whole output but main line was "pyserial or esptool directories not found next to this upload.py tool."
I googled it and found a thread in Arduino forum with this fix: https://forum.arduino.cc/t/pyserial-and-esptools-directory-error/671804/5
I don't understand anything that is done there, but I made the change to the file and it worked! So I thought it worth mentioning, maybe you can add it to the manual for future users.
Cheers for great project!

**Comment by epiller** [comment]
Great find! It appears to be one of many things Big Sur broke... If you're not using Arduino for anything else besides Klimerko, could you try the newest version (1.8.15) and see if that solves the issue without the file modification?
