### ISSUE TITLE
Export data to lokal 

### ISSUE THREAD

**Issue by y0d4a** [DesconBelgrade/Klimerko#26]
Zdravo,

jel moze da se setuj da uporedo mi salje data na lokalni monitoring sistem? konkretno zeleo bih da ga uvezem sa cacti?

**Comment by epiller** [comment]
To nazalost nije moguce sa postojecim firmware-om :(

**Comment by batica81** [comment]
Koliko se secam, kada se ukljuci debugging mod, podaci se ispisuju i na (pseudo) serijskom portu. Ako ti odgovara da uredjaj ukljucis u npr raspberry pi ili server koji se ne iskljucuje, mozes da pokupis odande.
