### ISSUE TITLE
Hiding sensors that do not have current data from vazduhgradjanima.rs

### ISSUE THREAD

**Issue by milos1986** [DesconBelgrade/Klimerko#3]
Default map view should imho hide the sensors with old PM data. Data older than e.g. 2h is arguably not useful for the visitors seeking current pollution data. Old data makes it harder to find current pollution data, as one needs to click around to find "alive" sensors. A feature request and the ideal case would be to display air quality for each sensor on the map directly, along with the time of measurement. A filter enabling one to define what "current data" is (e.g., 1h or 3h old) could be another nice feature.

**Comment by epiller** [comment]
I agree with you. This is on our roadmap and will be addressed.
