### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by TheLazarus89** [DesconBelgrade/Klimerko#30]
Arduino: 1.8.15 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Disabled (new aborts on oom), Disabled, All SSL ciphers (most compatible), 32KB cache + 32KB IRAM (balanced), Use pgm_read macros for IRAM/PROGMEM, 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"

remove core\core.a: The process cannot access the file because it is being used by another process.

Error compiling for board NodeMCU 1.0 (ESP-12E Module).

Executable segment sizes:

ICACHE : 32768           - flash instruction cache 

IROM   : 287860          - code in flash         (default or ICACHE_FLASH_ATTR) 

IRAM   : 30525   / 32768 - code in IRAM          (IRAM_ATTR, ISRs...) 

DATA   : 1696  )         - initialized variables (global, static) in RAM/HEAP 

RODATA : 7628  ) / 81920 - constants             (global, static) in RAM/HEAP 

BSS    : 31440 )         - zeroed variables      (global, static) in RAM/HEAP 

Sketch uses 327709 bytes (31%) of program storage space. Maximum is 1044464 bytes.

Global variables use 40764 bytes (49%) of dynamic memory, leaving 41156 bytes for local variables. Maximum is 81920 bytes.

esptool.py v3.0

Serial port COM1

Connecting........_____....._____....._____....._____....._____....._____.....____Traceback (most recent call last):

  File "C:\Users\Milisavljevic\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2/tools/upload.py", line 66, in <module>

    esptool.main(cmdline)

  File "C:/Users/Milisavljevic/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 3552, in main

    esp.connect(args.before, args.connect_attempts)

  File "C:/Users/Milisavljevic/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/3.0.2/tools/esptool\esptool.py", line 529, in connect

    raise FatalError('Failed to connect to %s: %s' % (self.CHIP_NAME, last_error))

esptool.FatalError: Failed to connect to ESP8266: Timed out waiting for packet header

_

the selected serial port _

 does not exist or your board is not connected

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

[https://prnt.sc/1q6laso]

Does someone know what is the problem?

**Comment by epiller** [comment]
Closing this issue
