### ISSUE TITLE
Bme280 merenje temperature.

### ISSUE THREAD

**Issue by Buljubasa** [DesconBelgrade/Klimerko#33]
Primetio sam da klimerko pokazuje dosta nizu temperaturu od onog napravljenog sa SHT11 koji sam stavio odmah pored.
Vidim da je programski stavljeno da pokazuje 4C manje od vrednosti koju sam BME280 salje.
BME280 hoce da salje nesto vise vrednosti ali to je obicno 0.5-1C, bar su neka moja iskustva takva ili ste imali module sa vecom greskom?

**Comment by epiller** [comment]
It's because the heat of the ESP8266 affects the sensor when it's in the 3D printed enclosure as well, [as stated in the firmware source here](https://github.com/DesconBelgrade/Klimerko/blob/cc9c3eb44948a695143bd9019689350339979e3d/Klimerko_Firmware/Klimerko_Firmware.ino#L308)
