### ISSUE TITLE
3d printer .stl files would be nice :)

### ISSUE THREAD

**Issue by retro-source** [DesconBelgrade/Klimerko#4]
3d printe .stl files would be nice :)

**Comment by dcabro** [comment]
Or any other acceptable file format for that matter. If anyone is willing to share their file, that'd be awesome. Thanks!

**Comment by epiller** [comment]
The STL files will be published and available for download somewhere before 15th of February :)

**Comment by epiller** [comment]
[It's available right now!](https://github.com/DesconBelgrade/Klimerko/tree/master/Klimerko_Printable_Case)

**Comment by dcabro** [comment]
Thank you so much! Awesome! 

You might want to further clarify that you don't need both Stand and Wall Mount, but you pick one depending on the mounting desires. Keep up the good work!
