### ISSUE TITLE
Klimerko FW is not compiling 

### ISSUE THREAD

**Issue by ilic5000** [DesconBelgrade/Klimerko#53]
I had a problem when compiling FW - Arduino IDE said that the result is missing (nothing is returned) when "(!wifiConnectionLost)" is false. I've fixed this issue by returning "Error" for that case, without it it wouldn't work. 

![image](https://user-images.githubusercontent.com/19806811/212201896-a856025c-eb69-4983-8f2b-147abcddc4fe.png)

https://github.com/DesconBelgrade/Klimerko/blob/master/Klimerko_Firmware/Klimerko_Firmware.ino#L790-L809

**Comment by epiller** [comment]
I've just installed Arduino IDE 2.0.3 in order to try and replicate this issue but it compiled without any issues. I'll fix that function anyways.

**Comment by epiller** [comment]
Fixed in [Firmware v2.1.1](https://github.com/DesconBelgrade/Klimerko/releases/tag/2.1.1).
