### ISSUE TITLE
Readme update needed - communication with NodeMCU on Windows10 needs a driver

### ISSUE THREAD

**Issue by ilic5000** [DesconBelgrade/Klimerko#54]
When I connected NodeMCU to my PC, Windows could not automatically install the required drivers and because of that device was not recognized (in the device manager it had a yellow icon and it said that drivers were not installed). After a quick search I've found this site:

https://www.silabs.com/developers/usb-to-uart-bridge-vcp-drivers?tab=downloads

And after installing [CP210x Universal Windows Driver](https://www.silabs.com/documents/public/software/CP210x_Universal_Windows_Driver.zip), everything worked perfectly. I got a new COM port  (COM4) as an option in Arduino IDE, it had only COM1 before the installation of drivers, and it did not work with that COM1.

It would be a good idea to add this in the Troubleshooting section of the main Readme.

**Comment by epiller** [comment]
- Link to CP2102 Windows driver added in [Software](https://github.com/DesconBelgrade/Klimerko#software) section of README. (271eb5a10059baa00250a45d28f8b2115a17c3f3)
- COM port ambiguity mentioned in [Uploading Firmware](https://github.com/DesconBelgrade/Klimerko#uploading-firmware) and [Updating Using Arduino IDE](https://github.com/DesconBelgrade/Klimerko#updating-using-arduino-ide) section of README. (e8887f4a5fb94abd6acefcb0480442c1946dc960)
