### ISSUE TITLE
Temp/humidity sensor requirement?

### ISSUE THREAD

**Issue by psyhomb** [DesconBelgrade/Klimerko#62]
Is this temp/humidity sensor required for this setup to work or we can assemble, flash and use Klimerko without it? Thanks

**Comment by epiller** [comment]
Nope! You can actually use it without any sensors if you want to play around. I only mentioned that in the [2.0.0 release notes](https://github.com/DesconBelgrade/Klimerko/releases/tag/2.0.0) so I'll consider putting it in the main README as well.  

From 2.0.0 release notes: 
> ## Works Without Sensor(s)
> Klimerko can now function without one or both sensors in case of a hardware problem.
> It detects if a sensor is missing or if it failed and omits sending values from that specific sensor in order to eliminate bogus data being sent and recovers the sensor if it has been connected (or starts working again) and initializes it, runs tests and starts sending data for that sensor again.
> And it does all this automatically even during operation! You could hot-swap your sensors! Or not. Nobody does that.

**Comment by psyhomb** [comment]
> Nope! You can actually use it without any sensors if you want to play around. I only mentioned that in the [2.0.0 release notes](https://github.com/DesconBelgrade/Klimerko/releases/tag/2.0.0) so I'll consider putting it in the main README as well.

Awesome, happy to hear that, given that I have trouble ordering temp/humidity sensor and I've already received all other components, particle sensor and microcontroller board (esp8266) I was wondering if I can assemble it and use it only to send pm data. Thank you
