### ISSUE TITLE
Pictures of Klimerko

### ISSUE THREAD

**Issue by misavasic** [DesconBelgrade/Klimerko#7]
Hi,
Can someone share pictures of assembly process of Klimerko or at least pictures of final product. I have all parts needed except 3D case but I am not so sure how final assembly should look like.
Thanks in advance

**Comment by epiller** [comment]
Sorry about that, I thought the instructions in the README were sufficient.  
You'll see the assembled "base" on the photos below, front and back.
I'll get some proper photos and put them in the documentation soon.
<img width="95" alt="klimerko-assembled-back" src="https://user-images.githubusercontent.com/26664052/75121169-7ca64080-5689-11ea-873d-d895de33199c.png"> <img width="93" alt="klimerko-assembled-front" src="https://user-images.githubusercontent.com/26664052/75121171-7e700400-5689-11ea-8cc1-bde9769f2045.png">

**Comment by misavasic** [comment]
Thanks. Instructions are detailed but as someone said "One Look Is Worth A Thousand Words". My goal is to build it without any soldering if possible. When assembled i will post manual and pictures here.
